# Generated by Django 5.0.3 on 2024-04-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorUser',
            fields=[
                ('employee_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=255)),
                ('photo', models.ImageField(default='default.jpg', upload_to='admin_photos/')),
                ('log_out_time', models.DateTimeField(default='1970-01-01 00:00:00')),
                ('address', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('phone_number', models.IntegerField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(default=0)),
                ('student_id', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(default='', max_length=255)),
                ('attendee', models.CharField(max_length=200, unique=True)),
                ('time', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('time', models.CharField(default='', max_length=50)),
                ('primary_location', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100, null=True, unique=True)),
                ('primary_location', models.CharField(default='', max_length=255)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
