# Generated by Django 5.0.3 on 2024-04-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SmartGAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorUser',
            fields=[
                ('employee_id', models.CharField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=255)),
                ('photo', models.ImageField(default='default.jpg', upload_to='admin_photos/')),
                ('log_out_time', models.DateTimeField(default='1970-01-01 00:00:00')),
                ('address', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('phone_number', models.CharField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('phoneNumber', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('attendee', models.CharField(max_length=200, unique=True)),
                ('time', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(primary_key=True, serialize=False)),
                ('time', models.CharField(default='', max_length=50)),
                ('primary_location', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.CharField(primary_key=True, serialize=False)),
                ('primary_location', models.CharField(default='', max_length=255)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
