/**
 * @file Manages the API slice for user-related data.
 */

import { createEntityAdapter, createSelector } from '@reduxjs/toolkit';
import { apiSlice } from '../../app/api/apiSlice';

/**
 * Create an entity adapter to manage user data in the Redux store.
 * @type {import('@reduxjs/toolkit').EntityAdapter}
 */
const usersAdapter = createEntityAdapter({});

/**
 * The initial state for the user data using the entity adapter.
 * @type {import('@reduxjs/toolkit').EntityState}
 */
const initialState = usersAdapter.getInitialState();

/**
 * Create an API slice for managing user-related data.
 * @type {import('../../app/api/apiSlice').ApiSlice}
 */
export const usersApiSlice = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    /**
     * Get users from the API.
     * @type {import('../../app/api/apiSlice').QueryEndpoint}
     */
    getUsers: builder.query({
      query: () => '/users',
      validateStatus: (response, result) => {
        return response.status === 200 && !result.isError;
      },
      transformResponse: (responseData) => {
        // Transform the response data by mapping '_id' to 'id' and set it in the Redux store
        const loadedUsers = responseData.map((user) => {
          user.id = user._id;
          return user;
        });
        // Set all users in the Redux store
        return usersAdapter.setAll(initialState, loadedUsers);
      },
      providesTags: (result, error, arg) => {
        if (result?.ids) {
          return [
            { type: 'User', id: 'List' }, // Tags to identify the list of users
            // Individual user tags
            ...result.ids.map((id) => ({ type: 'User', id })),
          ];
        }
        // Default tag for the user list
        else return [{ type: 'User', id: 'List' }];
      },
    }),

    /**
     * Add a new user to the API.
     * @type {import('../../app/api/apiSlice').MutationEndpoint}
     */
    addNewUser: builder.mutation({
      query: ({ newUser }) => ({
        url: '/users',
        method: 'POST',
        body: { ...newUser },
      }),
      // Invalidate the user list tag
      invalidatesTags: [{ type: 'User', id: 'List' }],
    }),

    /**
     * Update an existing user in the API.
     * @type {import('../../app/api/apiSlice').MutationEndpoint}
     */
    updateUser: builder.mutation({
      query: ({ newUser, id }) => ({
        url: `/users/${id}`,
        method: 'PATCH',
        body: { ...newUser },
      }),
      // Invalidate the specific user's tag
      invalidatesTags: (result, error, arg) => [{ type: 'User', id: arg.id }],
    }),

    /**
     * Delete an existing user from the API.
     * @type {import('../../app/api/apiSlice').MutationEndpoint}
     */
    deleteUser: builder.mutation({
      query: ({ id }) => ({
        url: `/users/${id}`,
        method: 'DELETE',
      }),
      // Invalidate the specific user's tag
      invalidatesTags: (result, error, arg) => [{ type: 'User', id: arg.id }],
    }),
  }),
});

/**
 * Hooks generated by the API slice for use in components.
 * @type {Object}
 * @property {import('../../app/api/apiSlice').QueryHook} useGetUsersQuery - Hook for getting users.
 * @property {import('../../app/api/apiSlice').MutationHook} useAddNewUserMutation - Hook for adding a new user.
 * @property {import('../../app/api/apiSlice').MutationHook} useUpdateUserMutation - Hook for updating an existing user.
 * @property {import('../../app/api/apiSlice').MutationHook} useDeleteUserMutation - Hook for deleting an existing user.
 */
export const {
  useGetUsersQuery,
  useAddNewUserMutation,
  useUpdateUserMutation,
  useDeleteUserMutation,
} = usersApiSlice;

/**
 * The result of the 'getUsers' query.
 * @type {import('../../app/api/apiSlice').QueryResult}
 */
export const selectUsersResult = usersApiSlice.endpoints.getUsers.select();

/**
 * Selector to retrieve user data from the result.
 * @type {import('@reduxjs/toolkit').OutputSelector}
 */
const selectUsersData = createSelector(
  selectUsersResult,
  (usersResult) => usersResult.data
);

/**
 * Select all users.
 * @type {import('@reduxjs/toolkit').OutputSelector}
 */
export const {
  selectAll: selectAllUsers,
  /**
   * Select a user by ID.
   * @type {import('@reduxjs/toolkit').OutputSelector}
   */
  selectById: selectUserById,
  /**
   * Select user IDs.
   * @type {import('@reduxjs/toolkit').OutputSelector}
   */
  selectIds: selectUserIds,
} = usersAdapter.getInitialState((state) => selectUsersData(state) ?? initialState);
