# Generated by Django 5.0.4 on 2024-06-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmanager',
            name='alert_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertmanager',
            name='alert_stopped',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertmanager',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alertmanager',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
