# Generated by Django 5.0.4 on 2024-06-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlertManagerApp', '0004_alter_alertmanager_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertmanager',
            name='alert_started',
        ),
        migrations.RemoveField(
            model_name='alertmanager',
            name='alert_stopped',
        ),
    ]
