# Generated by Django 5.0.4 on 2024-06-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertManagerApp', '0005_remove_alertmanager_alert_started_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmanager',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
