# Generated by Django 5.0.4 on 2024-06-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertManagerApp', '0002_alertmanager_alert_started_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmanager',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='alertmanager',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
