# Generated by Django 5.0.4 on 2024-06-01 20:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertManagerApp', '0003_alter_alertmanager_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmanager',
            name='location',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
