# Generated by Django 5.0.4 on 2024-05-03 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DeviceApp', '0002_locationdata_phonenumbers_delete_locationmanager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeviceApp.phonenumbers')),
            ],
            options={
                'unique_together': {('phone_number', 'timestamp')},
            },
        ),
    ]
