# Generated by Django 5.0.4 on 2024-05-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceApp', '0002_locationdata_phonenumbers_delete_locationmanager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbers',
            name='phone_number',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
