# Generated by Django 5.0.4 on 2024-05-06 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceApp', '0004_remove_phonenumbers_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumbers',
            old_name='address',
            new_name='email_address',
        ),
    ]
