# Generated by Django 5.0.4 on 2024-05-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceApp', '0005_rename_address_phonenumbers_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdata',
            name='alert',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='student_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
