# Generated by Django 5.0.4 on 2024-05-06 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceApp', '0003_alter_phonenumbers_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumbers',
            name='name',
        ),
    ]
